./x2dhfctl4t -bl -v
and

/x2dhfctl -bl -v

produce the following error messages:

 ... eFiles/x2dhf.dir/libxc_master.F90.o -o x2dhf  /home/jkob/github/4t/x2dhf/libxc/lib/libxc.a
 /usr/bin/ld: CMakeFiles/x2dhf.dir/libxc_master.F90.o: in function `__xc_f03_lib_m_MOD_xc_f03_func_set_fhc_enforcement':
 libxc_master.F90:(.text+0x4ff): undefined reference to `xc_func_set_fhc_enforcement'
 /usr/bin/ld: libxc_master.F90:(.text+0x50b): undefined reference to `xc_func_set_fhc_enforcement'

"./x2dhfctl -bt -v"  fails to handle tpool pthreads properly.

 Changes to be committed:
	modified:   CMakeLists.txt
	modified:   src/CMakeLists.txt
	new file:   x2dhfctl4t